# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_backtest.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow3(object):
    def setupUi(self, MainWindow3):
        MainWindow3.setObjectName("MainWindow3")
        MainWindow3.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow3)
        self.centralwidget.setObjectName("centralwidget")
        self.date_start = QtWidgets.QDateEdit(self.centralwidget)
        self.date_start.setGeometry(QtCore.QRect(60, 40, 110, 24))
        self.date_start.setObjectName("date_start")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 20, 60, 16))
        self.label.setObjectName("label")
        self.date_end = QtWidgets.QDateEdit(self.centralwidget)
        self.date_end.setGeometry(QtCore.QRect(200, 40, 110, 24))
        self.date_end.setObjectName("date_end")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 20, 60, 16))
        self.label_2.setObjectName("label_2")
        self.button_backtest = QtWidgets.QPushButton(self.centralwidget)
        self.button_backtest.setGeometry(QtCore.QRect(430, 490, 113, 32))
        self.button_backtest.setObjectName("button_backtest")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 20, 101, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.input_startMoney = QtWidgets.QTextEdit(self.centralwidget)
        self.input_startMoney.setGeometry(QtCore.QRect(340, 40, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_startMoney.setFont(font)
        self.input_startMoney.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_startMoney.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_startMoney.setDocumentTitle("")
        self.input_startMoney.setPlaceholderText("")
        self.input_startMoney.setObjectName("input_startMoney")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 80, 101, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.input_changeDays = QtWidgets.QTextEdit(self.centralwidget)
        self.input_changeDays.setGeometry(QtCore.QRect(100, 100, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_changeDays.setFont(font)
        self.input_changeDays.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_changeDays.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_changeDays.setDocumentTitle("")
        self.input_changeDays.setPlaceholderText("")
        self.input_changeDays.setObjectName("input_changeDays")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 90, 101, 21))
        self.label_5.setObjectName("label_5")
        self.input_monthRP_UpMpnth = QtWidgets.QTextEdit(self.centralwidget)
        self.input_monthRP_UpMpnth.setGeometry(QtCore.QRect(330, 120, 81, 21))
        self.input_monthRP_UpMpnth.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_monthRP_UpMpnth.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_monthRP_UpMpnth.setObjectName("input_monthRP_UpMpnth")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(240, 120, 101, 21))
        self.label_6.setObjectName("label_6")
        self.input_monthRP_smoothAVG = QtWidgets.QTextEdit(self.centralwidget)
        self.input_monthRP_smoothAVG.setGeometry(QtCore.QRect(330, 90, 81, 21))
        self.input_monthRP_smoothAVG.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_monthRP_smoothAVG.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_monthRP_smoothAVG.setObjectName("input_monthRP_smoothAVG")
        MainWindow3.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow3)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow3.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow3)
        self.statusbar.setObjectName("statusbar")
        MainWindow3.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow3)

    def retranslateUi(self, MainWindow3):
        _translate = QtCore.QCoreApplication.translate
        MainWindow3.setWindowTitle(_translate("MainWindow3", "回測"))
        self.label.setText(_translate("MainWindow3", "開始日期"))
        self.label_2.setText(_translate("MainWindow3", "結束日期"))
        self.button_backtest.setText(_translate("MainWindow3", "開始回測"))
        self.label_3.setText(_translate("MainWindow3", "開始資金(萬元)"))
        self.label_4.setText(_translate("MainWindow3", "換股天數(天)"))
        self.label_5.setText(_translate("MainWindow3", "往前平滑月份"))
        self.label_6.setText(_translate("MainWindow3", "連續升高月份"))


