# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_backtest.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow3(object):
    def setupUi(self, MainWindow3):
        MainWindow3.setObjectName("MainWindow3")
        MainWindow3.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow3)
        self.centralwidget.setObjectName("centralwidget")
        self.date_start = QtWidgets.QDateEdit(self.centralwidget)
        self.date_start.setGeometry(QtCore.QRect(60, 40, 110, 24))
        self.date_start.setObjectName("date_start")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 20, 60, 16))
        self.label.setObjectName("label")
        self.date_end = QtWidgets.QDateEdit(self.centralwidget)
        self.date_end.setGeometry(QtCore.QRect(200, 40, 110, 24))
        self.date_end.setObjectName("date_end")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 20, 60, 16))
        self.label_2.setObjectName("label_2")
        self.button_backtest = QtWidgets.QPushButton(self.centralwidget)
        self.button_backtest.setGeometry(QtCore.QRect(412, 490, 131, 32))
        self.button_backtest.setObjectName("button_backtest")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 20, 101, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.input_startMoney = QtWidgets.QTextEdit(self.centralwidget)
        self.input_startMoney.setGeometry(QtCore.QRect(340, 40, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_startMoney.setFont(font)
        self.input_startMoney.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_startMoney.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_startMoney.setDocumentTitle("")
        self.input_startMoney.setPlaceholderText("")
        self.input_startMoney.setObjectName("input_startMoney")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 80, 101, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.input_changeDays = QtWidgets.QTextEdit(self.centralwidget)
        self.input_changeDays.setGeometry(QtCore.QRect(100, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_changeDays.setFont(font)
        self.input_changeDays.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_changeDays.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_changeDays.setDocumentTitle("")
        self.input_changeDays.setPlaceholderText("")
        self.input_changeDays.setObjectName("input_changeDays")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(220, 80, 231, 101))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 229, 99))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(30, 70, 101, 21))
        self.label_6.setObjectName("label_6")
        self.input_monthRP_UpMpnth = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.input_monthRP_UpMpnth.setGeometry(QtCore.QRect(120, 70, 81, 21))
        self.input_monthRP_UpMpnth.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_monthRP_UpMpnth.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_monthRP_UpMpnth.setObjectName("input_monthRP_UpMpnth")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(30, 40, 101, 21))
        self.label_5.setObjectName("label_5")
        self.input_monthRP_smoothAVG = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.input_monthRP_smoothAVG.setGeometry(QtCore.QRect(120, 40, 81, 21))
        self.input_monthRP_smoothAVG.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_monthRP_smoothAVG.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_monthRP_smoothAVG.setObjectName("input_monthRP_smoothAVG")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(30, 10, 101, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.check_monthRP_pick = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.check_monthRP_pick.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.check_monthRP_pick.setText("")
        self.check_monthRP_pick.setObjectName("check_monthRP_pick")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(220, 190, 231, 101))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 229, 99))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setGeometry(QtCore.QRect(30, 70, 101, 21))
        self.label_8.setObjectName("label_8")
        self.input_PER_end = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.input_PER_end.setGeometry(QtCore.QRect(70, 70, 81, 21))
        self.input_PER_end.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_PER_end.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_PER_end.setObjectName("input_PER_end")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_9.setGeometry(QtCore.QRect(30, 40, 101, 21))
        self.label_9.setObjectName("label_9")
        self.input_PER_start = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.input_PER_start.setGeometry(QtCore.QRect(70, 40, 81, 21))
        self.input_PER_start.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_PER_start.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_PER_start.setObjectName("input_PER_start")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setGeometry(QtCore.QRect(50, 10, 101, 21))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.check_PER_pick = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.check_PER_pick.setGeometry(QtCore.QRect(10, 10, 21, 20))
        self.check_PER_pick.setText("")
        self.check_PER_pick.setObjectName("check_PER_pick")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setGeometry(QtCore.QRect(10, 190, 201, 101))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 199, 99))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_11.setGeometry(QtCore.QRect(30, 70, 101, 21))
        self.label_11.setObjectName("label_11")
        self.input_volumeAVG_days = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_3)
        self.input_volumeAVG_days.setGeometry(QtCore.QRect(110, 70, 81, 21))
        self.input_volumeAVG_days.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_volumeAVG_days.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_volumeAVG_days.setObjectName("input_volumeAVG_days")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_12.setGeometry(QtCore.QRect(30, 40, 101, 21))
        self.label_12.setObjectName("label_12")
        self.input_volume_money = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_3)
        self.input_volume_money.setGeometry(QtCore.QRect(110, 40, 81, 21))
        self.input_volume_money.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_volume_money.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_volume_money.setObjectName("input_volume_money")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_13.setGeometry(QtCore.QRect(30, 10, 101, 21))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.check_volume_pick = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.check_volume_pick.setGeometry(QtCore.QRect(10, 10, 111, 20))
        self.check_volume_pick.setText("")
        self.check_volume_pick.setObjectName("check_volume_pick")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.check_pickOneStock = QtWidgets.QCheckBox(self.centralwidget)
        self.check_pickOneStock.setGeometry(QtCore.QRect(40, 160, 101, 20))
        self.check_pickOneStock.setText("")
        self.check_pickOneStock.setObjectName("check_pickOneStock")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(60, 160, 101, 21))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_4.setGeometry(QtCore.QRect(10, 300, 201, 101))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 199, 99))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_15.setGeometry(QtCore.QRect(30, 70, 101, 21))
        self.label_15.setObjectName("label_15")
        self.input_price_low = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_4)
        self.input_price_low.setGeometry(QtCore.QRect(110, 70, 81, 21))
        self.input_price_low.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_price_low.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_price_low.setObjectName("input_price_low")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_16.setGeometry(QtCore.QRect(30, 40, 101, 21))
        self.label_16.setObjectName("label_16")
        self.input_price_high = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_4)
        self.input_price_high.setGeometry(QtCore.QRect(110, 40, 81, 21))
        self.input_price_high.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_price_high.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_price_high.setObjectName("input_price_high")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_17.setGeometry(QtCore.QRect(50, 10, 131, 21))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.check_price_pick = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.check_price_pick.setGeometry(QtCore.QRect(10, 10, 111, 20))
        self.check_price_pick.setText("")
        self.check_price_pick.setObjectName("check_price_pick")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.scrollArea_5 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_5.setGeometry(QtCore.QRect(220, 300, 231, 101))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 229, 99))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_18.setGeometry(QtCore.QRect(30, 70, 101, 21))
        self.label_18.setObjectName("label_18")
        self.input_PBR_end = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_5)
        self.input_PBR_end.setGeometry(QtCore.QRect(80, 70, 81, 21))
        self.input_PBR_end.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_PBR_end.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_PBR_end.setObjectName("input_PBR_end")
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_19.setGeometry(QtCore.QRect(30, 40, 101, 21))
        self.label_19.setObjectName("label_19")
        self.input_PBR_start = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_5)
        self.input_PBR_start.setGeometry(QtCore.QRect(80, 40, 81, 21))
        self.input_PBR_start.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_PBR_start.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_PBR_start.setObjectName("input_PBR_start")
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_20.setGeometry(QtCore.QRect(40, 10, 141, 21))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.check_PBR_pick = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.check_PBR_pick.setGeometry(QtCore.QRect(10, 10, 21, 20))
        self.check_PBR_pick.setText("")
        self.check_PBR_pick.setObjectName("check_PBR_pick")
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.scrollArea_6 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_6.setGeometry(QtCore.QRect(460, 80, 231, 101))
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 229, 99))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_21.setGeometry(QtCore.QRect(30, 70, 101, 21))
        self.label_21.setObjectName("label_21")
        self.input_ROE_end = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_6)
        self.input_ROE_end.setGeometry(QtCore.QRect(80, 70, 81, 21))
        self.input_ROE_end.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_ROE_end.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_ROE_end.setObjectName("input_ROE_end")
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_22.setGeometry(QtCore.QRect(30, 40, 101, 21))
        self.label_22.setObjectName("label_22")
        self.input_ROE_start = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_6)
        self.input_ROE_start.setGeometry(QtCore.QRect(80, 40, 81, 21))
        self.input_ROE_start.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_ROE_start.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_ROE_start.setObjectName("input_ROE_start")
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_23.setGeometry(QtCore.QRect(30, 10, 161, 21))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.check_ROE_pick = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_6)
        self.check_ROE_pick.setGeometry(QtCore.QRect(10, 10, 21, 20))
        self.check_ROE_pick.setText("")
        self.check_ROE_pick.setObjectName("check_ROE_pick")
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.button_backtest_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_backtest_2.setGeometry(QtCore.QRect(550, 490, 151, 32))
        self.button_backtest_2.setObjectName("button_backtest_2")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(0, 110, 101, 16))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.input_StockAmount = QtWidgets.QTextEdit(self.centralwidget)
        self.input_StockAmount.setGeometry(QtCore.QRect(100, 110, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_StockAmount.setFont(font)
        self.input_StockAmount.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_StockAmount.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_StockAmount.setDocumentTitle("")
        self.input_StockAmount.setPlaceholderText("")
        self.input_StockAmount.setObjectName("input_StockAmount")
        self.button_backtest_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_backtest_3.setGeometry(QtCore.QRect(560, 450, 131, 32))
        self.button_backtest_3.setObjectName("button_backtest_3")
        self.input_stockNumber = QtWidgets.QTextEdit(self.centralwidget)
        self.input_stockNumber.setGeometry(QtCore.QRect(500, 40, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_stockNumber.setFont(font)
        self.input_stockNumber.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_stockNumber.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_stockNumber.setDocumentTitle("")
        self.input_stockNumber.setPlaceholderText("")
        self.input_stockNumber.setObjectName("input_stockNumber")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(510, 20, 111, 16))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.scrollArea_7 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_7.setGeometry(QtCore.QRect(10, 410, 231, 101))
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 229, 99))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_26.setGeometry(QtCore.QRect(30, 70, 101, 21))
        self.label_26.setObjectName("label_26")
        self.input_yield_end = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_7)
        self.input_yield_end.setGeometry(QtCore.QRect(80, 70, 81, 21))
        self.input_yield_end.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_yield_end.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_yield_end.setObjectName("input_yield_end")
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_27.setGeometry(QtCore.QRect(30, 40, 101, 21))
        self.label_27.setObjectName("label_27")
        self.input_yield_start = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_7)
        self.input_yield_start.setGeometry(QtCore.QRect(80, 40, 81, 21))
        self.input_yield_start.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_yield_start.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_yield_start.setObjectName("input_yield_start")
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_28.setGeometry(QtCore.QRect(40, 10, 141, 21))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.check_yield_pick = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.check_yield_pick.setGeometry(QtCore.QRect(10, 10, 21, 20))
        self.check_yield_pick.setText("")
        self.check_yield_pick.setObjectName("check_yield_pick")
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_7)
        self.input_buyDay = QtWidgets.QTextEdit(self.centralwidget)
        self.input_buyDay.setGeometry(QtCore.QRect(570, 420, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_buyDay.setFont(font)
        self.input_buyDay.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_buyDay.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_buyDay.setDocumentTitle("")
        self.input_buyDay.setPlaceholderText("")
        self.input_buyDay.setObjectName("input_buyDay")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(620, 420, 81, 20))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.button_backtest_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_backtest_4.setGeometry(QtCore.QRect(280, 490, 131, 32))
        self.button_backtest_4.setObjectName("button_backtest_4")
        self.input_RecordHigh = QtWidgets.QTextEdit(self.centralwidget)
        self.input_RecordHigh.setGeometry(QtCore.QRect(100, 140, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_RecordHigh.setFont(font)
        self.input_RecordHigh.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_RecordHigh.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_RecordHigh.setDocumentTitle("")
        self.input_RecordHigh.setPlaceholderText("")
        self.input_RecordHigh.setObjectName("input_RecordHigh")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(0, 140, 101, 16))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        MainWindow3.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow3)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow3.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow3)
        self.statusbar.setObjectName("statusbar")
        MainWindow3.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow3)

    def retranslateUi(self, MainWindow3):
        _translate = QtCore.QCoreApplication.translate
        MainWindow3.setWindowTitle(_translate("MainWindow3", "回測"))
        self.label.setText(_translate("MainWindow3", "開始日期"))
        self.label_2.setText(_translate("MainWindow3", "結束日期"))
        self.button_backtest.setText(_translate("MainWindow3", "開始月營收回測"))
        self.label_3.setText(_translate("MainWindow3", "開始資金(萬元)"))
        self.label_4.setText(_translate("MainWindow3", "換股天數(天)"))
        self.label_6.setText(_translate("MainWindow3", "連續升高月份"))
        self.label_5.setText(_translate("MainWindow3", "往前平滑月份"))
        self.label_7.setText(_translate("MainWindow3", "月營收選股"))
        self.label_8.setText(_translate("MainWindow3", "最高"))
        self.label_9.setText(_translate("MainWindow3", "最低"))
        self.label_10.setText(_translate("MainWindow3", "本益比選股(PER)"))
        self.label_11.setText(_translate("MainWindow3", "平均天數"))
        self.label_12.setText(_translate("MainWindow3", "最低金額(元)"))
        self.label_13.setText(_translate("MainWindow3", "交易量選股"))
        self.label_14.setText(_translate("MainWindow3", "是否只挑一支股票"))
        self.label_15.setText(_translate("MainWindow3", "最低股價"))
        self.label_16.setText(_translate("MainWindow3", "最高股價"))
        self.label_17.setText(_translate("MainWindow3", "股價選股"))
        self.label_18.setText(_translate("MainWindow3", "最高"))
        self.label_19.setText(_translate("MainWindow3", "最低"))
        self.label_20.setText(_translate("MainWindow3", "股價淨值比選股(PBR)"))
        self.label_21.setText(_translate("MainWindow3", "最高"))
        self.label_22.setText(_translate("MainWindow3", "最低"))
        self.label_23.setText(_translate("MainWindow3", "股東權益報酬率選股(ROE)"))
        self.button_backtest_2.setText(_translate("MainWindow3", "開始回測PER&PBR"))
        self.label_24.setText(_translate("MainWindow3", "篩選股票數"))
        self.button_backtest_3.setText(_translate("MainWindow3", "開始定期定額回測"))
        self.label_25.setText(_translate("MainWindow3", "購買固定股票號碼"))
        self.label_26.setText(_translate("MainWindow3", "最高"))
        self.label_27.setText(_translate("MainWindow3", "最低"))
        self.label_28.setText(_translate("MainWindow3", "殖利率選股"))
        self.label_29.setText(_translate("MainWindow3", "號為購買日"))
        self.button_backtest_4.setText(_translate("MainWindow3", "開始創新高回測"))
        self.label_30.setText(_translate("MainWindow3", "幾天內創新高"))


