# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_main.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(10, 50, 211, 251))
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.treeView.setObjectName("treeView")
        self.input_stockNumber = QtWidgets.QTextEdit(self.centralwidget)
        self.input_stockNumber.setGeometry(QtCore.QRect(150, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_stockNumber.setFont(font)
        self.input_stockNumber.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_stockNumber.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_stockNumber.setDocumentTitle("")
        self.input_stockNumber.setPlaceholderText("")
        self.input_stockNumber.setObjectName("input_stockNumber")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 20, 81, 20))
        self.label.setObjectName("label")
        self.button_addStock = QtWidgets.QPushButton(self.centralwidget)
        self.button_addStock.setGeometry(QtCore.QRect(300, 17, 110, 32))
        self.button_addStock.setObjectName("button_addStock")
        self.button_deletStock = QtWidgets.QPushButton(self.centralwidget)
        self.button_deletStock.setGeometry(QtCore.QRect(409, 17, 113, 32))
        self.button_deletStock.setObjectName("button_deletStock")
        self.button_moveToInput = QtWidgets.QPushButton(self.centralwidget)
        self.button_moveToInput.setGeometry(QtCore.QRect(10, 310, 113, 32))
        self.button_moveToInput.setObjectName("button_moveToInput")
        self.button_getStockHistory = QtWidgets.QPushButton(self.centralwidget)
        self.button_getStockHistory.setGeometry(QtCore.QRect(435, 58, 113, 32))
        self.button_getStockHistory.setObjectName("button_getStockHistory")
        self.date_startDate = QtWidgets.QDateEdit(self.centralwidget)
        self.date_startDate.setGeometry(QtCore.QRect(290, 60, 131, 24))
        self.date_startDate.setMinimumDate(QtCore.QDate(1970, 1, 1))
        self.date_startDate.setObjectName("date_startDate")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 64, 60, 16))
        self.label_2.setObjectName("label_2")
        self.widget_SMA = QtWidgets.QWidget(self.centralwidget)
        self.widget_SMA.setGeometry(QtCore.QRect(230, 200, 221, 101))
        self.widget_SMA.setObjectName("widget_SMA")
        self.check_SMA = QtWidgets.QCheckBox(self.widget_SMA)
        self.check_SMA.setGeometry(QtCore.QRect(10, 20, 51, 51))
        self.check_SMA.setObjectName("check_SMA")
        self.input_SMA1 = QtWidgets.QTextEdit(self.widget_SMA)
        self.input_SMA1.setGeometry(QtCore.QRect(120, 10, 81, 21))
        self.input_SMA1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_SMA1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_SMA1.setObjectName("input_SMA1")
        self.label_SMA1 = QtWidgets.QLabel(self.widget_SMA)
        self.label_SMA1.setGeometry(QtCore.QRect(70, 10, 41, 21))
        self.label_SMA1.setObjectName("label_SMA1")
        self.input_SMA2 = QtWidgets.QTextEdit(self.widget_SMA)
        self.input_SMA2.setGeometry(QtCore.QRect(120, 40, 81, 21))
        self.input_SMA2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_SMA2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_SMA2.setObjectName("input_SMA2")
        self.label_SMA2 = QtWidgets.QLabel(self.widget_SMA)
        self.label_SMA2.setGeometry(QtCore.QRect(70, 40, 41, 21))
        self.label_SMA2.setObjectName("label_SMA2")
        self.label_SMA3 = QtWidgets.QLabel(self.widget_SMA)
        self.label_SMA3.setGeometry(QtCore.QRect(70, 70, 41, 21))
        self.label_SMA3.setObjectName("label_SMA3")
        self.input_SMA3 = QtWidgets.QTextEdit(self.widget_SMA)
        self.input_SMA3.setGeometry(QtCore.QRect(120, 70, 81, 21))
        self.input_SMA3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_SMA3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_SMA3.setObjectName("input_SMA3")
        self.check_stock = QtWidgets.QCheckBox(self.centralwidget)
        self.check_stock.setEnabled(False)
        self.check_stock.setGeometry(QtCore.QRect(230, 120, 87, 20))
        self.check_stock.setObjectName("check_stock")
        self.check_KD = QtWidgets.QCheckBox(self.centralwidget)
        self.check_KD.setGeometry(QtCore.QRect(320, 120, 87, 20))
        self.check_KD.setObjectName("check_KD")
        self.check_volume = QtWidgets.QCheckBox(self.centralwidget)
        self.check_volume.setGeometry(QtCore.QRect(410, 120, 87, 20))
        self.check_volume.setObjectName("check_volume")
        self.button_openPickWindow = QtWidgets.QPushButton(self.centralwidget)
        self.button_openPickWindow.setGeometry(QtCore.QRect(10, 480, 113, 32))
        self.button_openPickWindow.setObjectName("button_openPickWindow")
        self.button_getMonthRP = QtWidgets.QPushButton(self.centralwidget)
        self.button_getMonthRP.setGeometry(QtCore.QRect(310, 310, 113, 32))
        self.button_getMonthRP.setObjectName("button_getMonthRP")
        self.date_endDate = QtWidgets.QDateEdit(self.centralwidget)
        self.date_endDate.setGeometry(QtCore.QRect(290, 90, 131, 24))
        self.date_endDate.setMinimumDate(QtCore.QDate(1970, 1, 1))
        self.date_endDate.setObjectName("date_endDate")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 90, 60, 16))
        self.label_3.setObjectName("label_3")
        self.check_UseNewInfo = QtWidgets.QCheckBox(self.centralwidget)
        self.check_UseNewInfo.setGeometry(QtCore.QRect(440, 90, 87, 20))
        self.check_UseNewInfo.setObjectName("check_UseNewInfo")
        self.check_BollingerBands = QtWidgets.QCheckBox(self.centralwidget)
        self.check_BollingerBands.setGeometry(QtCore.QRect(230, 150, 87, 20))
        self.check_BollingerBands.setObjectName("check_BollingerBands")
        self.check_RSI = QtWidgets.QCheckBox(self.centralwidget)
        self.check_RSI.setGeometry(QtCore.QRect(320, 150, 87, 20))
        self.check_RSI.setObjectName("check_RSI")
        self.check_ADL = QtWidgets.QCheckBox(self.centralwidget)
        self.check_ADL.setGeometry(QtCore.QRect(410, 150, 87, 20))
        self.check_ADL.setObjectName("check_ADL")
        self.check_ADLs = QtWidgets.QCheckBox(self.centralwidget)
        self.check_ADLs.setGeometry(QtCore.QRect(410, 180, 87, 20))
        self.check_ADLs.setObjectName("check_ADLs")
        self.check_MACD = QtWidgets.QCheckBox(self.centralwidget)
        self.check_MACD.setGeometry(QtCore.QRect(320, 180, 87, 20))
        self.check_MACD.setObjectName("check_MACD")
        self.button_runSchedule = QtWidgets.QPushButton(self.centralwidget)
        self.button_runSchedule.setGeometry(QtCore.QRect(0, 520, 151, 32))
        self.button_runSchedule.setObjectName("button_runSchedule")
        self.button_stopSchedule = QtWidgets.QPushButton(self.centralwidget)
        self.button_stopSchedule.setGeometry(QtCore.QRect(150, 520, 161, 32))
        self.button_stopSchedule.setObjectName("button_stopSchedule")
        self.button_getDividend_yield = QtWidgets.QPushButton(self.centralwidget)
        self.button_getDividend_yield.setGeometry(QtCore.QRect(420, 310, 113, 32))
        self.button_getDividend_yield.setObjectName("button_getDividend_yield")
        self.button_getOperating_Margin = QtWidgets.QPushButton(self.centralwidget)
        self.button_getOperating_Margin.setGeometry(QtCore.QRect(200, 310, 113, 32))
        self.button_getOperating_Margin.setObjectName("button_getOperating_Margin")
        self.button_Operating_Margin_Ratio = QtWidgets.QPushButton(self.centralwidget)
        self.button_Operating_Margin_Ratio.setGeometry(QtCore.QRect(200, 340, 121, 32))
        self.button_Operating_Margin_Ratio.setObjectName("button_Operating_Margin_Ratio")
        self.button_getROE = QtWidgets.QPushButton(self.centralwidget)
        self.button_getROE.setGeometry(QtCore.QRect(200, 370, 113, 32))
        self.button_getROE.setObjectName("button_getROE")
        self.button_getFreeCF = QtWidgets.QPushButton(self.centralwidget)
        self.button_getFreeCF.setGeometry(QtCore.QRect(320, 340, 113, 32))
        self.button_getFreeCF.setObjectName("button_getFreeCF")
        self.button_getSCF = QtWidgets.QPushButton(self.centralwidget)
        self.button_getSCF.setGeometry(QtCore.QRect(320, 370, 113, 32))
        self.button_getSCF.setObjectName("button_getSCF")
        self.button_getICF = QtWidgets.QPushButton(self.centralwidget)
        self.button_getICF.setGeometry(QtCore.QRect(320, 400, 113, 32))
        self.button_getICF.setObjectName("button_getICF")
        self.button_getPCF = QtWidgets.QPushButton(self.centralwidget)
        self.button_getPCF.setGeometry(QtCore.QRect(310, 430, 131, 41))
        self.button_getPCF.setObjectName("button_getPCF")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "我的追蹤清單"))
        self.label.setText(_translate("MainWindow", "股票編號:"))
        self.button_addStock.setText(_translate("MainWindow", "新增"))
        self.button_deletStock.setText(_translate("MainWindow", "移除"))
        self.button_moveToInput.setText(_translate("MainWindow", "帶入"))
        self.button_getStockHistory.setText(_translate("MainWindow", "歷史股價紀錄"))
        self.label_2.setText(_translate("MainWindow", "開始日期:"))
        self.check_SMA.setText(_translate("MainWindow", "均線"))
        self.label_SMA1.setText(_translate("MainWindow", "SMA1"))
        self.label_SMA2.setText(_translate("MainWindow", "SMA2"))
        self.label_SMA3.setText(_translate("MainWindow", "SMA3"))
        self.check_stock.setText(_translate("MainWindow", "顯示股價"))
        self.check_KD.setText(_translate("MainWindow", "顯示KD值"))
        self.check_volume.setText(_translate("MainWindow", "顯示總量"))
        self.button_openPickWindow.setText(_translate("MainWindow", "開啟選股視窗"))
        self.button_getMonthRP.setText(_translate("MainWindow", "歷史月營收紀錄"))
        self.label_3.setText(_translate("MainWindow", "結束日期:"))
        self.check_UseNewInfo.setText(_translate("MainWindow", "使用最新資訊"))
        self.check_BollingerBands.setText(_translate("MainWindow", "顯示布林通道"))
        self.check_RSI.setText(_translate("MainWindow", "顯示RSI"))
        self.check_ADL.setText(_translate("MainWindow", "顯示ADL"))
        self.check_ADLs.setText(_translate("MainWindow", "顯示ADLs"))
        self.check_MACD.setText(_translate("MainWindow", "顯示MACD"))
        self.button_runSchedule.setText(_translate("MainWindow", "mysql股票Update"))
        self.button_stopSchedule.setText(_translate("MainWindow", "mysql股票Update Stop"))
        self.button_getDividend_yield.setText(_translate("MainWindow", "歷史殖利率紀錄"))
        self.button_getOperating_Margin.setText(_translate("MainWindow", "營業利益率紀錄"))
        self.button_Operating_Margin_Ratio.setText(_translate("MainWindow", "營業利益成長率"))
        self.button_getROE.setText(_translate("MainWindow", "歷史ROE紀錄"))
        self.button_getFreeCF.setText(_translate("MainWindow", "自由現金流紀錄"))
        self.button_getSCF.setText(_translate("MainWindow", "營業現金流紀錄"))
        self.button_getICF.setText(_translate("MainWindow", "投資現金流紀錄"))
        self.button_getPCF.setText(_translate("MainWindow", "股價現金流量比率"))


