# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_pick.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(600, 668)
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.treeView_pick = QtWidgets.QTreeView(self.centralwidget)
        self.treeView_pick.setGeometry(QtCore.QRect(10, 410, 571, 181))
        self.treeView_pick.setObjectName("treeView_pick")
        self.button_moveToInput = QtWidgets.QPushButton(self.centralwidget)
        self.button_moveToInput.setGeometry(QtCore.QRect(480, 590, 113, 32))
        self.button_moveToInput.setObjectName("button_moveToInput")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 251, 251))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 249, 249))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.Ana_ProfitAndLoss = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.Ana_ProfitAndLoss.setGeometry(QtCore.QRect(10, 0, 111, 31))
        self.Ana_ProfitAndLoss.setObjectName("Ana_ProfitAndLoss")
        self.input_OPR = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.input_OPR.setGeometry(QtCore.QRect(160, 60, 81, 21))
        self.input_OPR.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_OPR.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_OPR.setObjectName("input_OPR")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(30, 30, 91, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 121, 21))
        self.label_2.setObjectName("label_2")
        self.input_GPM = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.input_GPM.setGeometry(QtCore.QRect(160, 30, 81, 21))
        self.input_GPM.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_GPM.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_GPM.setObjectName("input_GPM")
        self.input_RPS = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.input_RPS.setGeometry(QtCore.QRect(160, 120, 81, 21))
        self.input_RPS.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_RPS.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_RPS.setObjectName("input_RPS")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 81, 21))
        self.label_3.setObjectName("label_3")
        self.Ana_BalanceSheet = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.Ana_BalanceSheet.setGeometry(QtCore.QRect(10, 90, 111, 31))
        self.Ana_BalanceSheet.setObjectName("Ana_BalanceSheet")
        self.input_EPS = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.input_EPS.setGeometry(QtCore.QRect(160, 180, 81, 21))
        self.input_EPS.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_EPS.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_EPS.setObjectName("input_EPS")
        self.Ana_CPAndLoss = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.Ana_CPAndLoss.setGeometry(QtCore.QRect(10, 150, 111, 31))
        self.Ana_CPAndLoss.setObjectName("Ana_CPAndLoss")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(40, 180, 101, 21))
        self.label_4.setObjectName("label_4")
        self.button_pick = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.button_pick.setGeometry(QtCore.QRect(140, 210, 113, 32))
        self.button_pick.setObjectName("button_pick")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 260, 211, 141))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 209, 139))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.button_pick_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.button_pick_2.setGeometry(QtCore.QRect(90, 100, 113, 32))
        self.button_pick_2.setObjectName("button_pick_2")
        self.input_monthRP_smoothAVG = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.input_monthRP_smoothAVG.setGeometry(QtCore.QRect(110, 40, 81, 21))
        self.input_monthRP_smoothAVG.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_monthRP_smoothAVG.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_monthRP_smoothAVG.setObjectName("input_monthRP_smoothAVG")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 101, 21))
        self.label_5.setObjectName("label_5")
        self.input_monthRP_UpMpnth = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.input_monthRP_UpMpnth.setGeometry(QtCore.QRect(110, 70, 81, 21))
        self.input_monthRP_UpMpnth.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_monthRP_UpMpnth.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_monthRP_UpMpnth.setObjectName("input_monthRP_UpMpnth")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setGeometry(QtCore.QRect(20, 70, 101, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setGeometry(QtCore.QRect(60, 0, 101, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.button_openBackWindow = QtWidgets.QPushButton(self.centralwidget)
        self.button_openBackWindow.setGeometry(QtCore.QRect(450, 360, 113, 32))
        self.button_openBackWindow.setObjectName("button_openBackWindow")
        MainWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        MainWindow2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow2)
        self.statusbar.setObjectName("statusbar")
        MainWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "財報挑選"))
        self.button_moveToInput.setText(_translate("MainWindow2", "帶入"))
        self.Ana_ProfitAndLoss.setText(_translate("MainWindow2", "營益分析彙總表"))
        self.label.setText(_translate("MainWindow2", "毛利率(%)大於"))
        self.label_2.setText(_translate("MainWindow2", "營業利益率(%)大於"))
        self.label_3.setText(_translate("MainWindow2", "每股參考淨值"))
        self.Ana_BalanceSheet.setText(_translate("MainWindow2", "資產負債彙總表"))
        self.Ana_CPAndLoss.setText(_translate("MainWindow2", "綜合損益彙總表"))
        self.label_4.setText(_translate("MainWindow2", "基本每股盈餘(元)"))
        self.button_pick.setText(_translate("MainWindow2", "開始篩選"))
        self.button_pick_2.setText(_translate("MainWindow2", "開始篩選"))
        self.label_5.setText(_translate("MainWindow2", "往前平滑月份"))
        self.label_6.setText(_translate("MainWindow2", "連續升高月份"))
        self.label_7.setText(_translate("MainWindow2", "逐步升高篩選"))
        self.button_openBackWindow.setText(_translate("MainWindow2", "開啟回測視窗"))


