# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_pick.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(700, 670)
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.treeView_pick = QtWidgets.QTreeView(self.centralwidget)
        self.treeView_pick.setGeometry(QtCore.QRect(10, 410, 571, 181))
        self.treeView_pick.setObjectName("treeView_pick")
        self.button_moveToInput = QtWidgets.QPushButton(self.centralwidget)
        self.button_moveToInput.setGeometry(QtCore.QRect(480, 590, 113, 32))
        self.button_moveToInput.setObjectName("button_moveToInput")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 251, 251))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 249, 249))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.Ana_ProfitAndLoss = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.Ana_ProfitAndLoss.setGeometry(QtCore.QRect(10, 0, 111, 31))
        self.Ana_ProfitAndLoss.setObjectName("Ana_ProfitAndLoss")
        self.input_OPR = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.input_OPR.setGeometry(QtCore.QRect(160, 60, 81, 21))
        self.input_OPR.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_OPR.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_OPR.setObjectName("input_OPR")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(30, 30, 91, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 121, 21))
        self.label_2.setObjectName("label_2")
        self.input_GPM = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.input_GPM.setGeometry(QtCore.QRect(160, 30, 81, 21))
        self.input_GPM.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_GPM.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_GPM.setObjectName("input_GPM")
        self.input_RPS = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.input_RPS.setGeometry(QtCore.QRect(160, 120, 81, 21))
        self.input_RPS.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_RPS.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_RPS.setObjectName("input_RPS")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 81, 21))
        self.label_3.setObjectName("label_3")
        self.Ana_BalanceSheet = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.Ana_BalanceSheet.setGeometry(QtCore.QRect(10, 90, 111, 31))
        self.Ana_BalanceSheet.setObjectName("Ana_BalanceSheet")
        self.input_EPS = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.input_EPS.setGeometry(QtCore.QRect(160, 180, 81, 21))
        self.input_EPS.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_EPS.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_EPS.setObjectName("input_EPS")
        self.Ana_CPAndLoss = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.Ana_CPAndLoss.setGeometry(QtCore.QRect(10, 150, 111, 31))
        self.Ana_CPAndLoss.setObjectName("Ana_CPAndLoss")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(40, 180, 101, 21))
        self.label_4.setObjectName("label_4")
        self.button_pick = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.button_pick.setGeometry(QtCore.QRect(140, 210, 113, 32))
        self.button_pick.setObjectName("button_pick")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 260, 211, 141))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 209, 139))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.button_pick_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.button_pick_2.setGeometry(QtCore.QRect(90, 100, 113, 32))
        self.button_pick_2.setObjectName("button_pick_2")
        self.input_monthRP_smoothAVG = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.input_monthRP_smoothAVG.setGeometry(QtCore.QRect(110, 40, 81, 21))
        self.input_monthRP_smoothAVG.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_monthRP_smoothAVG.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_monthRP_smoothAVG.setObjectName("input_monthRP_smoothAVG")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 101, 21))
        self.label_5.setObjectName("label_5")
        self.input_monthRP_UpMpnth = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.input_monthRP_UpMpnth.setGeometry(QtCore.QRect(110, 70, 81, 21))
        self.input_monthRP_UpMpnth.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_monthRP_UpMpnth.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_monthRP_UpMpnth.setObjectName("input_monthRP_UpMpnth")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setGeometry(QtCore.QRect(20, 70, 101, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setGeometry(QtCore.QRect(60, 0, 101, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.button_openBackWindow = QtWidgets.QPushButton(self.centralwidget)
        self.button_openBackWindow.setGeometry(QtCore.QRect(370, 590, 113, 32))
        self.button_openBackWindow.setObjectName("button_openBackWindow")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setGeometry(QtCore.QRect(220, 300, 211, 101))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 209, 99))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.input_volum = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_3)
        self.input_volum.setGeometry(QtCore.QRect(80, 60, 111, 21))
        self.input_volum.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_volum.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_volum.setObjectName("input_volum")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 101, 21))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_10.setGeometry(QtCore.QRect(60, 0, 101, 31))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.check_volum_Max = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.check_volum_Max.setGeometry(QtCore.QRect(30, 30, 87, 20))
        self.check_volum_Max.setObjectName("check_volum_Max")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.scrollArea_4 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_4.setGeometry(QtCore.QRect(260, 10, 211, 91))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 209, 89))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.input_price_high = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_4)
        self.input_price_high.setGeometry(QtCore.QRect(90, 30, 111, 21))
        self.input_price_high.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_price_high.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_price_high.setObjectName("input_price_high")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_11.setGeometry(QtCore.QRect(60, 0, 101, 31))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_12.setGeometry(QtCore.QRect(10, 60, 101, 21))
        self.label_12.setObjectName("label_12")
        self.input_price_low = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_4)
        self.input_price_low.setGeometry(QtCore.QRect(90, 60, 111, 21))
        self.input_price_low.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_price_low.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_price_low.setObjectName("input_price_low")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.scrollArea_5 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_5.setGeometry(QtCore.QRect(260, 100, 211, 91))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 209, 89))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.input_PBR_high = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_5)
        self.input_PBR_high.setGeometry(QtCore.QRect(90, 30, 111, 21))
        self.input_PBR_high.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_PBR_high.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_PBR_high.setObjectName("input_PBR_high")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_13.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_14.setGeometry(QtCore.QRect(60, 0, 101, 31))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_15.setGeometry(QtCore.QRect(10, 60, 101, 21))
        self.label_15.setObjectName("label_15")
        self.input_PBR_low = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_5)
        self.input_PBR_low.setGeometry(QtCore.QRect(90, 60, 111, 21))
        self.input_PBR_low.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_PBR_low.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_PBR_low.setObjectName("input_PBR_low")
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.scrollArea_6 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_6.setGeometry(QtCore.QRect(260, 190, 211, 91))
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 209, 89))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.input_PER_high = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_6)
        self.input_PER_high.setGeometry(QtCore.QRect(90, 30, 111, 21))
        self.input_PER_high.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_PER_high.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_PER_high.setObjectName("input_PER_high")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_16.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_17.setGeometry(QtCore.QRect(60, 0, 101, 31))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_18.setGeometry(QtCore.QRect(10, 60, 101, 21))
        self.label_18.setObjectName("label_18")
        self.input_PER_low = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_6)
        self.input_PER_low.setGeometry(QtCore.QRect(90, 60, 111, 21))
        self.input_PER_low.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_PER_low.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_PER_low.setObjectName("input_PER_low")
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.scrollArea_7 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_7.setGeometry(QtCore.QRect(430, 300, 211, 91))
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 209, 89))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.input_ROE_high = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_7)
        self.input_ROE_high.setGeometry(QtCore.QRect(90, 30, 111, 21))
        self.input_ROE_high.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_ROE_high.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_ROE_high.setObjectName("input_ROE_high")
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_19.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_20.setGeometry(QtCore.QRect(60, 0, 101, 31))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_21.setGeometry(QtCore.QRect(10, 60, 101, 21))
        self.label_21.setObjectName("label_21")
        self.input_ROE_low = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_7)
        self.input_ROE_low.setGeometry(QtCore.QRect(90, 60, 111, 21))
        self.input_ROE_low.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_ROE_low.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_ROE_low.setObjectName("input_ROE_low")
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_7)
        self.scrollArea_8 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_8.setGeometry(QtCore.QRect(470, 10, 211, 91))
        self.scrollArea_8.setWidgetResizable(True)
        self.scrollArea_8.setObjectName("scrollArea_8")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 209, 89))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.input_yiled_high = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_8)
        self.input_yiled_high.setGeometry(QtCore.QRect(90, 30, 111, 21))
        self.input_yiled_high.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_yiled_high.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_yiled_high.setObjectName("input_yiled_high")
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents_8)
        self.label_22.setGeometry(QtCore.QRect(0, 30, 101, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents_8)
        self.label_23.setGeometry(QtCore.QRect(60, 0, 101, 31))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents_8)
        self.label_24.setGeometry(QtCore.QRect(0, 60, 101, 21))
        self.label_24.setObjectName("label_24")
        self.input_yiled_low = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_8)
        self.input_yiled_low.setGeometry(QtCore.QRect(90, 60, 111, 21))
        self.input_yiled_low.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_yiled_low.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_yiled_low.setObjectName("input_yiled_low")
        self.scrollArea_8.setWidget(self.scrollAreaWidgetContents_8)
        MainWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menubar.setObjectName("menubar")
        MainWindow2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow2)
        self.statusbar.setObjectName("statusbar")
        MainWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "財報挑選"))
        self.button_moveToInput.setText(_translate("MainWindow2", "帶入"))
        self.Ana_ProfitAndLoss.setText(_translate("MainWindow2", "營益分析彙總表"))
        self.label.setText(_translate("MainWindow2", "毛利率(%)大於"))
        self.label_2.setText(_translate("MainWindow2", "營業利益率(%)大於"))
        self.label_3.setText(_translate("MainWindow2", "每股參考淨值"))
        self.Ana_BalanceSheet.setText(_translate("MainWindow2", "資產負債彙總表"))
        self.Ana_CPAndLoss.setText(_translate("MainWindow2", "綜合損益彙總表"))
        self.label_4.setText(_translate("MainWindow2", "基本每股盈餘(元)"))
        self.button_pick.setText(_translate("MainWindow2", "開始篩選"))
        self.button_pick_2.setText(_translate("MainWindow2", "開始篩選"))
        self.label_5.setText(_translate("MainWindow2", "往前平滑月份"))
        self.label_6.setText(_translate("MainWindow2", "連續升高月份"))
        self.label_7.setText(_translate("MainWindow2", "逐步升高篩選"))
        self.button_openBackWindow.setText(_translate("MainWindow2", "開啟回測視窗"))
        self.label_8.setText(_translate("MainWindow2", "交易量(元)"))
        self.label_10.setText(_translate("MainWindow2", "交易量篩選"))
        self.check_volum_Max.setText(_translate("MainWindow2", "取最大交易量"))
        self.label_9.setText(_translate("MainWindow2", "股價範圍(高)"))
        self.label_11.setText(_translate("MainWindow2", "股價範圍篩選"))
        self.label_12.setText(_translate("MainWindow2", "股價範圍(低)"))
        self.label_13.setText(_translate("MainWindow2", "PBR(高)"))
        self.label_14.setText(_translate("MainWindow2", "股價淨值比篩選"))
        self.label_15.setText(_translate("MainWindow2", "PBR(低)"))
        self.label_16.setText(_translate("MainWindow2", "PER(高)"))
        self.label_17.setText(_translate("MainWindow2", "本益比篩選"))
        self.label_18.setText(_translate("MainWindow2", "PER(低)"))
        self.label_19.setText(_translate("MainWindow2", "ROE(高)"))
        self.label_20.setText(_translate("MainWindow2", "股東權益報酬率"))
        self.label_21.setText(_translate("MainWindow2", "ROE(低)"))
        self.label_22.setText(_translate("MainWindow2", "殖利率範圍(高)"))
        self.label_23.setText(_translate("MainWindow2", "殖利率範圍篩選"))
        self.label_24.setText(_translate("MainWindow2", "殖利率範圍(低)"))


