# 開發環境設定檔 - MySQL
database:
  type: mysql
  mysql:
    user: root
    password: b78924
    host: localhost
    port: 3307
    databasename: Demo

data:
  yield_dir: ../yieldInfo
  month_dir: ../monthRP
  season_dir: ../seasonInfo

migration:
  batch_size: 500